apiVersion: v1
kind: Namespace
metadata:
  name: spire

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: spire-database
  namespace: spire

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spire-database
  namespace: spire
  labels:
    app: spire-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spire-database
  serviceName: spire-database
  template:
    metadata:
      namespace: spire
      labels:
        app: spire-database
    spec:
      containers:
        - name: spire-database
          image: postgres:11
          env:
            - name: POSTGRES_USER
              value: spire
            - name: POSTGRES_PASSWORD
              value: MYSECRET
            - name: POSTGRES_DB
              value: spire
            - name: PGDATA
              value: /var/lib/postgresql/data/spire
          ports:
            - name: postgres
              containerPort: 5432
          livenessProbe:
            tcpSocket:
              port: 5432
            failureThreshold: 2
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 3
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
              readOnly: false
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
        namespace: spire
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

---

kind: Service
apiVersion: v1
metadata:
  name: spire-database
  namespace: spire
spec:
  ports:
  - protocol: TCP
    port: 5432
    targetPort: postgres
  selector:
    app: spire-database
