node:
  id: "id_02"
  cluster: "cluster_02"
static_resources:
  listeners:
  - name: web_to_echo_mtls_listener
    address:
      socket_address:
        address: 127.0.0.1
        port_value: 8001
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          idle_timeout: 1s
          codec_type: auto
          access_log:
          - name: envoy.file_access_log
            config:
              path: "/tmp/envoy-to-envoy-mtls.log"
          stat_prefix: ingress_http
          route_config:
            name: service_route
            virtual_hosts:
            - name: web_to_echo_mtls
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: web_to_echo_mtls
          http_filters:
          - name: envoy.router
  - name: web_to_echo_tls_listener
    address:
      socket_address:
        address: 127.0.0.1
        port_value: 8002
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          idle_timeout: 1s
          codec_type: auto
          access_log:
          - name: envoy.file_access_log
            config:
              path: "/tmp/envoy-to-envoy-tls.log"
          stat_prefix: ingress_http
          route_config:
            name: service_route
            virtual_hosts:
            - name: web_to_echo_tls
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: web_to_echo_tls
          http_filters:
          - name: envoy.router

  clusters:
  - name: spire_agent
    connect_timeout: 0.25s
    http2_protocol_options: {}
    hosts:
      - pipe:
          path: /tmp/agent.sock
  - name: web_to_echo_mtls
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: ROUND_ROBIN
    hosts:
      - socket_address:
          address: echo
          port_value: 8001
    tls_context:
      common_tls_context:
        tls_certificate_sds_secret_configs:
          - name: "spiffe://domain.test/web-server"
            sds_config:
              api_config_source:
                api_type: GRPC
                grpc_services:
                  envoy_grpc:
                    cluster_name: spire_agent
        validation_context_sds_secret_config:
          name: "spiffe://domain.test"
          sds_config:
            api_config_source:
              api_type: GRPC
              grpc_services:
                envoy_grpc:
                  cluster_name: spire_agent
        tls_params:
          ecdh_curves:
            - X25519:P-256:P-521:P-384
  - name: web_to_echo_tls
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: ROUND_ROBIN
    hosts:
      - socket_address:
          address: echo
          port_value: 8002
    tls_context:
      common_tls_context:
        validation_context_sds_secret_config:
          name: "spiffe://domain.test"
          sds_config:
            api_config_source:
              api_type: GRPC
              grpc_services:
                envoy_grpc:
                  cluster_name: spire_agent
        tls_params:
          ecdh_curves:
            - X25519:P-256:P-521:P-384
