name: stalebot
on:
  schedule:
  # Random minute number to avoid GH scheduler stampede
  - cron: '39 22 * * *'

jobs:
  process-stale-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/stale@997185467fa4f803885201cee163a9f38240193d # v10.1.1
      with:
        days-before-issue-stale: 365 # 1 year
        days-before-issue-close: 30
        stale-issue-label: "stale"
        exempt-issue-labels: "blocked,next-gen" # Ignore blocked and next-gen issues
        stale-issue-message: "This issue is stale because it has been open for 365 days with no activity."
        close-issue-message: "This issue was closed because it has been inactive for 30 days since being marked as stale."
        days-before-pr-stale: -1 # Don't handle PRs
        days-before-pr-close: -1 # Don't handle PRs

  process-stale-blocked-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/stale@997185467fa4f803885201cee163a9f38240193d # v10.1.1
      with:
        only-labels: "blocked"
        days-before-issue-stale: 30
        days-before-issue-close: -1 # Don't close blocked issues
        stale-issue-label: "stale"
        stale-issue-message: "This issue has been in the blocked state for 30 days, marking as stale so the blocking issue is re-checked."
        days-before-pr-stale: -1 # Don't handle PRs
        days-before-pr-close: -1 # Don't handle PRs
